spring.application.name=gateway-server

eureka.instance.preferIpAddress= true
eureka.client.registerWithEureka= true
eureka.client.fetchRegistry= true
eureka.client.serviceUrl.defaultZone= http://localhost:9095/eureka

#zipkin.baseUrl: http://localhost:9411

gateway.host=localhost
gateway.port=9097


spring.cloud.gateway.discovery.locator.enabled= true
spring.cloud.gateway.discovery.locator.lower-case-service-id= true


spring.config.import=optional:configserver:http://localhost:9096
spring.cloud.gateway.routes={id=service-routes, uri=lb://**, predicates=[Path=/**]}
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#logging.level.root=DEBUG
#logging.level.io.micrometer=DEBUG
#logging.level.io.opentelemetry=TRACE
#logging.level.org.springframework.cloud.gateway=TRACE
#management.tracing.sampling.probability=1.0
#management.otlp.tracing.endpoint=http://localhost:9411/api/v2/spans
#management.endpoints.web.exposure.include=prometheus
server.port=9097